# appium配置信息
platformName: Android

# 模拟器
platformVersion: 5.1.1
deviceName: 127.0.0.1:62001

# 真机
#platformVersion: 8.1.0
#udid: ZSJZSOTKJVRSJRDQ
#deviceName: OPPO R15

# 真机
#platformVersion: 9
#udid: f312d56e
#deviceName: OnePlus 5

# APP启动相关
#appname: wdkl.manager.v1.0.14.apk
app: D:/Python3/code/care_doctor/app/wdkl.manager.v1.0.14.apk
appPackage: doctor.wdklian.com
appActivity: doctor.wdklian.com.ui.activity.SplashActivity
ip: 127.0.0.1
port: 4723

# 测试覆盖开关按钮，True是继续测试，False是重新安装
noReset: False

# 开启中文输入
unicodeKeyboard: True
resetKeyboard: True

# 开启验证Toast信息
automationName: uiautomator2